# Generated by Django 5.0.2 on 2024-04-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortear', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaSorteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('sorteo', models.ManyToManyField(to='sortear.sorteo')),
            ],
        ),
    ]
