# Generated by Django 5.0.2 on 2024-04-13 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortear', '0003_rename_sorteo_categoriasorteo_sorteos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriasorteo',
            options={'verbose_name': 'categoriaSorteo', 'verbose_name_plural': 'categoriasSorteo'},
        ),
        migrations.AlterModelOptions(
            name='sorteo',
            options={'verbose_name': 'sorteo', 'verbose_name_plural': 'sorteos'},
        ),
        migrations.RemoveField(
            model_name='categoriasorteo',
            name='sorteos',
        ),
        migrations.AddField(
            model_name='sorteo',
            name='categoria',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sortear.categoriasorteo'),
        ),
    ]
