# Generated by Django 5.0.4 on 2024-04-13 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortear', '0004_alter_categoriasorteo_options_alter_sorteo_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sorteo',
            name='categoria',
        ),
        migrations.RenameModel(
            old_name='CategoriaSorteo',
            new_name='CategoriaPremio',
        ),
        migrations.CreateModel(
            name='PremioSorteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoriaPremio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premio', to='sortear.categoriapremio')),
                ('sorteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premio', to='sortear.sorteo')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenPremio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='sorteo')),
                ('premio', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='imagen', to='sortear.premiosorteo')),
            ],
        ),
        migrations.DeleteModel(
            name='ImagenSorteo',
        ),
    ]
