# Generated by Django 5.0.4 on 2024-04-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortear', '0005_remove_sorteo_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premiosorteo',
            old_name='CategoriaPremio',
            new_name='categoriaPremio',
        ),
        migrations.RemoveField(
            model_name='imagenpremio',
            name='premio',
        ),
        migrations.AddField(
            model_name='premiosorteo',
            name='imagenPremio',
            field=models.ManyToManyField(blank=True, to='sortear.imagenpremio'),
        ),
    ]
