# Generated by Django 5.0.4 on 2024-04-13 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortear', '0006_rename_categoriapremio_premiosorteo_categoriapremio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiosorteo',
            name='categoriaPremio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premio', to='sortear.categoriapremio'),
        ),
        migrations.RemoveField(
            model_name='premiosorteo',
            name='imagenPremio',
        ),
        migrations.AddField(
            model_name='premiosorteo',
            name='imagenPremio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sortear.imagenpremio'),
        ),
    ]
