# Generated by Django 5.0.4 on 2024-04-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sortear', '0007_alter_premiosorteo_categoriapremio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriapremio',
            options={'verbose_name': 'categoriaPremio', 'verbose_name_plural': 'categoriasPremios'},
        ),
        migrations.AddField(
            model_name='premiosorteo',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
